"""Color palette and style constants for the application."""

# Main palette — 3 chromatic elements only
FUNDO = "#f0f2f5"
DOMINANTE = "#003e63"
TEXTO = "#19374f"
NEUTRO = "#aaaaaa"

# Functional colors (system states only)
ERRO = "#cc0000"
AVISO = "#b87c00"
STATUS_OK = "#1c5a59"

# UI element colors
HEADER_BG = DOMINANTE
HEADER_FG = "#ffffff"

BTN_PRIMARY_BG = DOMINANTE
BTN_PRIMARY_FG = "#ffffff"
BTN_PRIMARY_HOVER = "#002a45"

BTN_SECONDARY_BG = "transparent"
BTN_SECONDARY_FG = DOMINANTE
BTN_SECONDARY_BORDER = DOMINANTE
BTN_SECONDARY_HOVER = "#e8edf2"

TAB_ACTIVE_BG = DOMINANTE
TAB_ACTIVE_FG = "#ffffff"
TAB_INACTIVE_BG = "#f7f8fa"
TAB_INACTIVE_FG = NEUTRO

CARD_BG = "#ffffff"
CARD_BORDER = "#dde1e7"
CARD_RADIUS = 8

ENTRY_BG = "#f7f8fa"
ENTRY_BORDER = "#dde1e7"
ENTRY_ERROR_BORDER = ERRO
ENTRY_RADIUS = 5

SECTION_TITLE_COLOR = DOMINANTE
BODY_TEXT_COLOR = TEXTO
AUX_TEXT_COLOR = NEUTRO
FIELD_LABEL_COLOR = NEUTRO

STATUS_WARN = AVISO

# Font settings
FONT_FAMILY = "Segoe UI"
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 10
FONT_SIZE_FIELD_LABEL = 10
FONT_SIZE_TITLE = 11
FONT_SIZE_HEADER = 18

# Layout
MAX_CONTENT_WIDTH = 720
