"""Color palette and style constants for the application."""

# Main palette
FUNDO = "#eeebe2"
DOMINANTE = "#003e63"
ACENTO = "#1c5a59"
TEXTO = "#19374f"
NEUTRO = "#8e8985"

# Functional colors
ERRO = "#cc0000"
AVISO = "#b87c00"

# UI element colors
HEADER_BG = DOMINANTE
HEADER_FG = "#ffffff"
BTN_PRIMARY_BG = DOMINANTE
BTN_PRIMARY_FG = "#ffffff"
BTN_PRIMARY_HOVER = ACENTO
BTN_SECONDARY_BG = ACENTO
BTN_SECONDARY_FG = "#ffffff"
BTN_SECONDARY_HOVER = ACENTO
TAB_ACTIVE_BG = DOMINANTE
TAB_ACTIVE_FG = "#ffffff"
TAB_INACTIVE_BG = "#ffffff"
TAB_INACTIVE_FG = NEUTRO
ENTRY_BG = "#ffffff"
ENTRY_BORDER = NEUTRO
ENTRY_ERROR_BORDER = ERRO
STATUS_OK = ACENTO
STATUS_WARN = AVISO
SECTION_TITLE_COLOR = TEXTO
BODY_TEXT_COLOR = TEXTO
AUX_TEXT_COLOR = NEUTRO

# Font settings
FONT_FAMILY = "Segoe UI"
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 10
FONT_SIZE_TITLE = 14
FONT_SIZE_HEADER = 18
